// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMBxz1SEchnEEfmnRckw-tSEc8UGfFmo',
    appId: '1:488726549710:web:d2dd77b71e3091220bac9f',
    messagingSenderId: '488726549710',
    projectId: 'djin-notes',
    authDomain: 'djin-notes.firebaseapp.com',
    storageBucket: 'djin-notes.appspot.com',
    measurementId: 'G-BP0ZDDM7HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXRQO1e3oT4pLCZCscFobVU0XnB0rw4g8',
    appId: '1:488726549710:android:26eefa5c28dcb7d00bac9f',
    messagingSenderId: '488726549710',
    projectId: 'djin-notes',
    storageBucket: 'djin-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcsa65QMQLWl56JsLCct8m0gu0r_XfuSw',
    appId: '1:488726549710:ios:779fda6932b109360bac9f',
    messagingSenderId: '488726549710',
    projectId: 'djin-notes',
    storageBucket: 'djin-notes.appspot.com',
    iosClientId: '488726549710-6rfd9bh499csaqoork5k2ctgbdjpv0m7.apps.googleusercontent.com',
    iosBundleId: 'com.djinworks.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcsa65QMQLWl56JsLCct8m0gu0r_XfuSw',
    appId: '1:488726549710:ios:779fda6932b109360bac9f',
    messagingSenderId: '488726549710',
    projectId: 'djin-notes',
    storageBucket: 'djin-notes.appspot.com',
    iosClientId: '488726549710-6rfd9bh499csaqoork5k2ctgbdjpv0m7.apps.googleusercontent.com',
    iosBundleId: 'com.djinworks.notes',
  );
}
